[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.0",
    "fastmcp>=2.3.3",
    "mcp[cli]>=1.8.0",
    "typer>=0.15.3",
]
